id: PD0441C6A
initial_creation_type: input
source_metadata:
  title: Ucchuṣma Series
  language: en
  description: 'Texts related to Ucchuṣma (sme brtsegs), a wrathful deity who is associated
    with the purification of defilements and whose name is sometimes given as Bhurkuṃkūṭa:'
  volume:
    71e45cf08f7e425c9c9adcb641a92c88:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    8f2c1205275f41e08043343503e3f557:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
    25286785c1d240b5bd14ce8a8d3e7815:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    46d5407a89134176bfb4a652060f6ebd:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Practices
created_at: '2022-03-01T06:28:10.168769'
last_modified_at: '2022-03-01T06:28:10.168775'
